services:
  app:
    build: .
    image: teamturnersolutions/equiptrack:demov3
    ports:
      - "9002:9002"
    volumes:
      - ./prisma:/app/prisma
    environment:
      - DATABASE_URL=file:/app/prisma/dev.db
      - NODE_ENV=production
      - TZ=America/New_York
